// In-memory adapter exercises the real Edge handler. It does NOT validate PostgreSQL/RLS.
import fs from 'node:fs';
import {stripTypeScriptTypes} from 'node:module';
import * as core from '../../week2-core.mjs';
export const demoCard=()=>{const d=core.emptyCard();d.candidates.forEach((c,i)=>core.fields.forEach(([k])=>c[k]=`候選${i+1}：校園午休觀察，${k}待訪談確認`));d.reason='可以接觸有午休限制的同學';d.reconsider='如果排隊不是主要困擾就重新選題';d.statement='午休只有五十分鐘的學生買餐時需要等候，仍需驗證時間代價';d.interviewees=['同學 A，課後詢問','同學 B，社團詢問','同學 C，午休詢問'];d.questions=['上一次買餐時發生什麼？','當時怎麼處理？'];d.contact_confirmed=d.questions_checked=true;return d;};
export async function harness({modelFails=false,directions=[],reserveNull=false}={}){
 const tables={classes:[{id:'class-a',name:'測試班（非正式學生）'},{id:'class-b',name:'其他班'}],teacher_classes:[{teacher_id:'teacher-a',class_id:'class-a'}],student_sessions:[],week1_submissions:[],week2_submissions:[],week1_ai_feedback_latest:[],learning_versions:[],week2_ai_requests:[],week2_settings:[]};
 const hash=async s=>Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))).toString('hex');
 async function student(id='TEST-1',submitted=true,classId='class-a') {const token='fixture-token-'+id+'-1234567890';tables.student_sessions.push({class_id:classId,student_id:id,expires_at:'2099-01-01',token_hash:await hash(token)});tables.week1_submissions.push({class_id:classId,student_id:id,student_name:'測試同學',status:submitted?'submitted':'draft',observed_problem:'午休排隊',known_fact:'昨天本人排隊',unverified_assumption:'其他同學也困擾'});return token;}
 let sequence=0;
 const db={auth:{getUser:async jwt=>({data:{user:jwt==='teacher-token'?{id:'teacher-a'}:null},error:jwt==='teacher-token'?null:'expired'})},from(name){let filter=()=>true,operation='select',values,one=false,sortKey,ascending=true,limit=Infinity;const chain={select(){return chain},eq(k,v){return chain.match({[k]:v})},match(obj){const old=filter;filter=r=>old(r)&&Object.entries(obj).every(([k,v])=>r[k]===v);return chain},in(k,v){const old=filter;filter=r=>old(r)&&v.includes(r[k]);return chain},order(k,opt={}){sortKey=k;ascending=opt.ascending!==false;return chain},limit(n){limit=n;return chain},maybeSingle(){one=true;return chain},single(){one=true;return chain},insert(v){operation='insert';values=v;return chain},upsert(v){operation='upsert';values=v;return chain},update(v){operation='update';values=v;return chain},then(resolve,reject){try{const t=tables[name];if(!t)throw Error('unknown table '+name);let rows=t.filter(filter);if(operation==='insert'||operation==='upsert'){let existing=operation==='upsert'?t.find(r=>r.class_id===values.class_id):null;if(existing){Object.assign(existing,structuredClone(values));rows=[existing];}else{const r={id:'id'+(++sequence),version:1,created_at:new Date().toISOString(),updated_at:new Date().toISOString(),...structuredClone(values)};t.push(r);rows=[r];}}if(operation==='update'){rows.forEach(r=>Object.assign(r,structuredClone(values),{version:(r.version||0)+1,updated_at:new Date().toISOString()}));}if(name==='week2_submissions'&&operation!=='select')rows.forEach(r=>tables.learning_versions.push({class_id:r.class_id,student_id:r.student_id,week:2,version:r.version,snapshot:structuredClone(r),created_at:new Date().toISOString()}));if(sortKey)rows.sort((a,b)=>String(a[sortKey]).localeCompare(String(b[sortKey]))*(ascending?1:-1));rows=rows.slice(0,limit);return Promise.resolve({data:structuredClone(one?rows[0]||null:rows),error:null}).then(resolve,reject);}catch(e){return Promise.reject(e).then(resolve,reject);}}};return chain;},async rpc(name,a){if(name!=='reserve_week2_ai')throw Error(name);if(reserveNull)return {data:null};const t=tables.week2_ai_requests,scope=t.filter(r=>r.class_id===a.cid&&r.student_id===a.sid);if(scope.some(r=>r.content_hash===a.h)||scope.length>=a.lim)return {data:null};const id='ai'+(++sequence);t.push({id,class_id:a.cid,student_id:a.sid,content_hash:a.h,kind:a.k,model:a.m,prompt_version:a.p,submission_version:a.v,state:'pending',created_at:new Date().toISOString()});return {data:id};}};
 const feedback={status:'revise',strength:'人物與情境清楚',gaps:['補充一次真實事件'],assumptions:['頻率尚未驗證'],questions:['上次何時發生？','當時怎麼處理？'],next_action:'記錄一次實際事件',directions};let calls=0,inputs=[];
 const modelFetch=async(url,opts)=>{calls++;inputs.push(JSON.parse(opts.body));return modelFails?new Response('{}',{status:503}):Response.json({choices:[{message:{content:JSON.stringify(feedback)}}],usage:{total_tokens:100}});};
 let source=fs.readFileSync(new URL('../../supabase/functions/week2-api/index.ts',import.meta.url),'utf8').replace(/^import .*;\n/gm,'');source=stripTypeScriptTypes(source).replace('Deno.serve(','return (');
 const names=Object.keys(core),handler=new Function('createClient','Deno','fetch',...names,source)(()=>db,{env:{get:k=>k==='OPENAI_API_KEY'?'test-only-secret':'test'}},modelFetch,...names.map(n=>core[n]));
 async function call(body,jwt){const r=await handler(new Request('http://localhost/functions/v1/week2-api',{method:'POST',headers:{'Content-Type':'application/json',...(jwt?{Authorization:'Bearer '+jwt}:{})},body:JSON.stringify(body)}));return {status:r.status,body:await r.json()};}
 return {tables,student,handler,call,get modelCalls(){return calls},inputs};
}
